# Generated by Django 2.1.5 on 2020-03-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200325_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Item')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Price')),
                ('toppings', models.ManyToManyField(blank=True, related_name='toppings', to='orders.Topping')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='topping_one',
        ),
        migrations.RemoveField(
            model_name='order',
            name='topping_three',
        ),
        migrations.RemoveField(
            model_name='order',
            name='topping_two',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='orderItems', to='orders.OrderItem'),
        ),
    ]
