# Generated by Django 2.1.5 on 2020-03-26 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200326_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='price',
            name='item',
        ),
        migrations.RemoveField(
            model_name='price',
            name='size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ManyToManyField(blank=True, related_name='items', to='orders.Order'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topping',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.Item'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
