# Generated by Django 2.1.5 on 2020-03-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200326_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='topping_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
