# Generated by Django 2.1.5 on 2020-04-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_menu_item_topping_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(max_length=60),
        ),
    ]
