# Generated by Django 2.1.5 on 2020-04-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200407_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='item',
        ),
        migrations.AddField(
            model_name='order_item',
            name='toppings',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
    ]
